### ISSUE TITLE
Add start URL to be '/' with perhaps query param for homescreen launch?

### ISSUE THREAD

**Issue by gauntface** [PolymerLabs/progressive-webapp-config#1]
Just handy for adding to homescreen with a consistent start URL - This is in the manifest.json

**Comment by robdodson** [comment]
Just gotta make sure you give the proper sw response for /?homescreen=1 or whatever or you may accidentally get an offline dino.

**Comment by addyosmani** [comment]
Rob bet me to it. We can definitely add the query param but need to do so carefully.

**Comment by gauntface** [comment]
Boooo this is a tad pants really.

For now I'd say close this issue because it's going to be mega fragile (i.e. to easy for developer to change the value not knowing it breaks offline support unless it's altered).
